# Write your code here :-)
#This program says hello and asks for the user's named
print('Hello, world!')
print('What is your name?')
myName = input()
print('It is good to meet you,', myName)
print('The length of your name is:')
print(len(myName))
print('What is your age?')
myAge = input()
print('You will be', str(int(myAge) + 8), 'in 8 years.')
